# Generated by Django 4.2 on 2023-04-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('rollno', models.IntegerField()),
                ('mobileno', models.BigIntegerField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
