# Generated by Django 4.2 on 2023-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_hosteller',
            field=models.TextField(default=True),
        ),
    ]
