# Generated by Django 4.2 on 2023-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0002_users_is_hosteller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_hosteller',
            field=models.TextField(default=False),
        ),
    ]
