# Generated by Django 4.2 on 2023-04-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0003_alter_users_is_hosteller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_hosteller',
        ),
    ]
